openapi: "3.0.1"
info:
  title: "Test"
  version: "1.0.0"
paths:
  /test/resource/{resourceId}/{otherId}:
    get:
      parameters:
        - name: "resourceId"
          in: "path"
          required: true
          description: "Some path param"
          schema:
            type: "string"
        - name: "otherId"
          in: "path"
          required: true
          description: "Some path param"
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content: {}
        400:
          description: "400 response"
      security:
        - Some-Authorizer: []
      x-amazon-apigateway-integration:
        type: "http"
        requestParameters:
          integration.request.header.accept: "method.request.header.accept"
        passthroughBehavior: "when_no_match"
        httpMethod: "GET"
        responses:
          200:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"